### ISSUE TITLE
Ripgrep not found on MacOS 12.6

### ISSUE THREAD

**Issue by bonny** [tadashi-aikawa/obsidian-another-quick-switcher#112]
I can't get the Grep command to work. I get the "You need to install Ripgrep..."-message.

Obisidan 0.16.3
Another Quick Switcher 7.0.1

RipGrep is installed, running this from terminal:

```
$ rg --version
ripgrep 13.0.0
-SIMD -AVX (compiled)
```

Error in Obsididan console:

<img width="774" alt="CleanShot 2022-09-28 at 09 12 37@2x" src="https://user-images.githubusercontent.com/221570/192712557-25a1ef51-5435-4aed-8818-7f43573184f6.png">

I saw #79 but no info there helped me.

**Comment by tadashi-aikawa** [comment]
Hi, @bonny :)

Where do you add the "rg" command to the PATH? (OS environment variable setting?  .zshrc?)

**Comment by bonny** [comment]
I install it via Brew so i'm not sure how the path-thingie works. I'll see if I can add it manually to the path somewhere.

**Comment by bonny** [comment]
Ok, I did manually add the path to `.zshrc` and restarted Obsidian, but still the same message. Not sure how Obsidian finds commands and how to modify the path it searches in.

**Comment by tadashi-aikawa** [comment]
@bonny 
Thank you for your reply. Unfortunately, I can't test on macOS but I should implement it to be able to set the absolute path of ripgrep executing.

Please wait for the next release 🙏 

P.S. Adding the path to `.zhsrc` is not working because "ripgrep" is executed from the Obsidian process (not from zsh)

**Comment by andymac4182** [comment]
Looks like this is how you will need to do it on mac @bonny https://stackoverflow.com/questions/22465332/setting-path-environment-variable-in-osx-permanently

**Comment by tadashi-aikawa** [comment]
Thank you for your follow! @andymac4182 :)

I have implemented the new option and will release it soon 👍 

![image](https://user-images.githubusercontent.com/9500018/193193144-ca6220db-9c50-4799-a857-b38499f9f9e4.png)

Maybe, it is so difficult for many people, especially not an engineers 😅

**Comment by tadashi-aikawa** [comment]
Released in [v7.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.1.0) 🚀 

@bonny Please confirm it 🙏

**Comment by bonny** [comment]
@tadashi-aikawa it works now! thank you very much for such a quick solution.

**Comment by tadashi-aikawa** [comment]
Great 👍

**Comment by kalmir** [comment]
Uuuf, made it work, thanks @tadashi-aikawa for adding the ripgrep command setting.

It just took me a while to understand I need to put the path to this setting. Because "rg" worked in the terminal, it wasn't immediately clear to me that "ripgrep command" is the setting that needs changing.

For anyone figuring out what to put in the setting on macOS, I did:
→ `brew --pregix rg` to find the path, opt/homebrew/opt/ripgrep, in my case 
→ added /bin/rg at the end and 
→ put that in the AQS ripgrep command setting (so /opt/homebrew/opt/ripgrep/bin/rg in my case)
