### ISSUE TITLE
FR: target commands

### ISSUE THREAD

**Issue by ggstrader** [tadashi-aikawa/obsidian-another-quick-switcher#149]
Being able to search and execute commands would make it so the command palette and quick switcher are unified into one hotkey. "Better Command Palette" has a lot of overlap with this plugin. In my opinion this is the better plugin as it gives more control, but this is one thing the plugin is missing.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.

**Comment by Kani3D** [comment]
I would like to explain further since i have the same FR.

There are two core plugins by default in Obsidian.
1. Quick Switcher ctrl+ ?
2. Command Palette ctrl+p

Another quickswitcher expands 1. but cant toggle commands from the command palette.

The FR would be either to have a toggle during search i.e. "Mod + ` "
To access the command palette/excute commands or a prefix.
There is a plugin called quickswitcher++. If you type > before your search it will search the commands and execute them.

**Comment by tadashi-aikawa** [comment]
Hi, @Kani3D :)

Thank you for your explanation. I now understand why you would want such a feature.

However, at this time, we do not plan to implement a command list feature. That said, if many other users need it, I will consider it. Could you create a separate issue for this matter?
