### ISSUE TITLE
request: An option to show the aliases 

### ISSUE THREAD

**Issue by ShravanSunder** [tadashi-aikawa/obsidian-another-quick-switcher#233]
It would be great for alias options to show up in the modal
![2024-04-28 0459 Obsidian rw Chia Jeng Yang bookid-40039907 - shravan-pkm - Obsidian v1 5 12](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/5294949/15a48423-d99b-443e-accb-81fcb6dc2e52)

For example, my readwies notes filenames only have bookIds.  but the aliases have the author and titile.  I would love to see them here.  When the modal pops up, its sorted by the recently highlighted books and it'd be nice to see the titles there.

**Comment by tadashi-aikawa** [comment]
Thank you for your feature request, @ShravanSunder :)

I understand the need to see author names and titles in the modal, especially when the filenames only include book IDs. Just to clarify, are you saying that the 'Show aliases on top' option is insufficient because aliases do not appear unless there is a word match?

**Comment by ShravanSunder** [comment]
@tadashi-aikawa Hi!  yes, i have that option turned on.  In the screen above tho i haven't typed anything in, its kinda a recent files list.   It would be great if the aliases actually show up in the text display, so i remember which references i was using.  

I would like the aliases to always show if they exist even without search.

i've very bad at remembering book ids 🙈

As always, thanks for the amazing plugin!

**Comment by ShravanSunder** [comment]
thank you!
