### ISSUE TITLE
Count inserts into file towards frequency as well

### ISSUE THREAD

**Issue by waynemsmith** [tadashi-aikawa/obsidian-another-quick-switcher#29]
Would go useful to count insertion of link into current files as as frequency hit same as if it was opened or modified. 

I think using this plugin to replace the `[[` search would be awesome. So if you are using it to add links to files, you don't get the benefit of the frequency in the search.

**Comment by tadashi-aikawa** [comment]
Hi, @waynemsmith. Thank you for creating an issue :)

But, I am sorry because I cannot understand what you want. Could you tell me more details with specific examples?

**Comment by waynemsmith** [comment]
HI, sure let me elaborate.

I try to use the `[[` during meetings to quickly tag e.g. a person's name in real time. `[[` gives the same search problem of presenting older information at to the top of the search as you are typing which your plugin solves. So I am now trying to rather use "recents option" in the plugin, instead of `[[`, to insert links into the editor as I type (using `CMD-SHIFT-E` then find item, then `OPTION-ENTER` to paste). However, because pasting the link does not update the file's `last open date`, the next time you go into the "recents options", and want to paste same link, the item you previously pasted is not at the top of the search option. It would be awesome to somehow "remember" the file's `last-linked-to date` and use that to improve the search as well. It may be difficult to do though, as file properties comes with `last-opened-date` as standard,  but there is probably no simple way to get a property that can be used for `last-linked-to date` which can be used to bring recently linked notes to the top of the search.

**Comment by tadashi-aikawa** [comment]
Thank you very much! I have understood what and why you need them.

I'm wondering whether to implement that feature on Another Quick Switcher because it would be better not to implement it on a quick switcher but on auto-completion.

I have been developing another Obsidian plugin named [Various Complements] that enables you to complete words like IDE's auto-completion. One of the plugin's features, [Internal link complement] suggests and completes the text with internal links without input `[[`.

If you prefer the above [Internal link complement] except for the order of suggestions, I'll consider implementing it not on Another Quick Switcher but on [Various Complements]. What do you think?

[Internal link complement]: https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Internal%20link%20complement/
[Various Complements]: https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/

**Comment by waynemsmith** [comment]
Thanks for the quick feedback. I have have installed [Various Complements](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/) and trying it out! Looks good. Definitely would be good to have it prioritise more recently linked and accessed notes, as top item matched when typing is some cases very old,  which makes the process of linking just a little inefficient.

**Comment by tadashi-aikawa** [comment]
I will try to implement in https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/114 👍

**Comment by tadashi-aikawa** [comment]
@waynemsmith 
I have released `Various Complements` (not `Another Quick Switcher`) beta versions that include what you want.

If you use BRAT, I hope you can use them 🙏 

[For details]
https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/114#issuecomment-1100829447

**Comment by tadashi-aikawa** [comment]
I have released `Various Complements` [v6.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0).

So let me close this issue :)
