### ISSUE TITLE
sort alphabetically option in sort priority

### ISSUE THREAD

**Issue by svonjoi** [tadashi-aikawa/obsidian-another-quick-switcher#91]
Hi

I would make custom search with traditional alphabeticall sort so I can type matching characters, for example "~" and see ordered results

![Obsidian_2022-08-21_15-54-20](https://user-images.githubusercontent.com/58810368/185794490-d60420bc-c4ed-41db-a5b8-8ab702bddeca.jpg)

thanks

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @svonjoi :)

I agree with you 👍

**Comment by tadashi-aikawa** [comment]
Released in [v6.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.2.0) 🚀

**Comment by FelipeRearden** [comment]
> Released in [v6.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.2.0) 🚀 

On my end, working-reflect on version v6.2.0 Obsidian Mobile  1.3.1 on iPadOS

Thank you very much @tadashi-aikawa !!!!

---

@tadashi-aikawa just one idea related to this FR ...

💡 How about a new variation of `Alphabetical` where we have 
**Z->A** instead of A->Z ????

I am suggesting this based on Daily Notes (YYYY-mm-dd) where we might want to have 2022 and 2021 notes before 2020 notes  when typing `202`

📸 My Daily Notes Folder
![image](https://user-images.githubusercontent.com/85180696/186893690-5092ea7b-a7b1-4b11-ace7-f09f7628d3e5.jpeg)

Just an idea, let me know if I can create a new issue :)

Have a great day ☀️

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
I see. I'll release it next release 👍

**Comment by FelipeRearden** [comment]
> @FelipeRearden 
> 
> I see. I'll release it next release 👍 

Thank you very much @tadashi-aikawa !!!!!!!!!!!

**Comment by svonjoi** [comment]
Thanks you @tadashi-aikawa :)
